#This script generates random arrays of different sizes, and types (random, sorted, reverse-sorter, arrays with repeated elements)
#It then calls the impmentation of heapsort,

import csv
import numpy as np

print("Generating random arrays")

arr1 = np.random.randint(0, 10000000, 100)
arr2 = np.random.randint(0, 10000000, 1000)
arr3 = np.random.randint(0, 10000000, 10000)
arr4 = np.random.randint(0, 10000000, 100000)
arr5 = np.random.randint(0, 10000000, 1000000)
arr6 = np.random.randint(0, 10000000, 10000000)

#Sort arrays in ascending order using python's built-in sorted() function
print("Sorting arrays in ascending order")
sorted_arr1 = sorted(arr1)
sorted_arr2 = sorted(arr2)
sorted_arr3 = sorted(arr3)
sorted_arr4 = sorted(arr4)
sorted_arr5 = sorted(arr5)
sorted_arr6 = sorted(arr6)

#Sort arrays in descending order using python's built-in sorted() function
print("Sorting arrays in descending order")
sorted_arr1_desc = sorted(arr1, reverse=True)
sorted_arr2_desc = sorted(arr2, reverse=True)
sorted_arr3_desc = sorted(arr3, reverse=True)
sorted_arr4_desc = sorted(arr4, reverse=True)
sorted_arr5_desc = sorted(arr5, reverse=True)
sorted_arr6_desc = sorted(arr6, reverse=True)

#Arrays with repeated elements
#This are generated by just reducing the randomization space

print("Generating arrays with repeated elements")

arr1_rep = np.random.randint(0, 100, 100)
arr2_rep = np.random.randint(0, 100, 1000)
arr3_rep = np.random.randint(0, 100, 10000)
arr4_rep = np.random.randint(0, 100, 100000)
arr5_rep = np.random.randint(0, 100, 1000000)
arr6_rep = np.random.randint(0, 100, 10000000)

#Measure time and memory usage of heapsort on each array
time_random = []
time_sorted = []
time_sorted_desc = []
time_sorted_rep = []

memory_random = []
memory_sorted = []
memory_sorted_desc = []
memory_sorted_rep = []

# Measure time and memory usage of heapsort on each sorted array (random)
print("Measuring time and memory usage of heapsort on random arrays")
for arr in [arr1, arr2, arr3, arr4, arr5, arr6]:
    #Write arr to a csv file
    with open('arr_random.csv', 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(arr)
    #Call heapsort.py on the csv file
    import subprocess
    subprocess.run(['python', 'heapsort.py', '--input_file', 'arr_random.csv', '--output_file', 'sorted_arr_random.csv'])  
    #Read the stats from the text file

    with open('stats.txt', 'r') as f:
        stats = f.read().split(',')
        time_random.append(float(stats[0]))
        memory_random.append(float(stats[1]))

#Save data to a csv file
with open('results_random.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Array Size', 'Time (s)', 'Memory (KB)'])
    for i in range(len(time_random)):
        writer.writerow([10**(i+2), time_random[i], memory_random[i]])


# Measure time and memory usage of heapsort on each sorted array (ascending)
print("Measuring time and memory usage of heapsort on sorted arrays (ascending)")
for arr in [sorted_arr1, sorted_arr2, sorted_arr3, sorted_arr4, sorted_arr5, sorted_arr6]:
    #Write arr to a csv file
    with open('arr_sorted.csv', 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(arr)
    #Call heapsort.py on the csv file
    subprocess.run(['python', 'heapsort.py', '--input_file', 'arr_sorted.csv', '--output_file', 'sorted_arr_sorted.csv'])  
    #Read the stats from the text file

    with open('stats.txt', 'r') as f:
        stats = f.read().split(',')
        time_sorted.append(float(stats[0]))
        memory_sorted.append(float(stats[1]))

#Save data to a csv file
with open('results_sorted.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Array Size', 'Time (s)', 'Memory (KB)'])
    for i in range(len(time_sorted)):
        writer.writerow([10**(i+2), time_sorted[i], memory_sorted[i]])
    
    



# Measure time and memory usage of heapsort on each sorted array (descending)
print("Measuring time and memory usage of heapsort on sorted arrays (descending)")
for arr in [sorted_arr1_desc, sorted_arr2_desc, sorted_arr3_desc, sorted_arr4_desc, sorted_arr5_desc, sorted_arr6_desc]:
    #Write arr to a csv file
    with open('arr_sorted_desc.csv', 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(arr)
    #Call heapsort.py on the csv file
    subprocess.run(['python', 'heapsort.py', '--input_file', 'arr_sorted_desc.csv', '--output_file', 'sorted_arr_sorted_desc.csv'])  
    #Read the stats from the text file

    with open('stats.txt', 'r') as f:
        stats = f.read().split(',')
        time_sorted_desc.append(float(stats[0]))
        memory_sorted_desc.append(float(stats[1]))

#Save data to a csv file
with open('results_sorted_desc.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Array Size', 'Time (s)', 'Memory (KB)'])
    for i in range(len(time_sorted_desc)):
        writer.writerow([10**(i+2), time_sorted_desc[i], memory_sorted_desc[i]])

# Measure time and memory usage of heapsort on each sorted array (with repeated elements)
print("Measuring time and memory usage of heapsort on arrays with repeated elements")
for arr in [arr1_rep, arr2_rep, arr3_rep, arr4_rep, arr5_rep, arr6_rep]:
    #Write arr to a csv file
    with open('arr_sorted_rep.csv', 'w', newline='') as csvfile:
        writer = csv.writer(csvfile)
        writer.writerow(arr)
    #Call heapsort.py on the csv file
    subprocess.run(['python', 'heapsort.py', '--input_file', 'arr_sorted_rep.csv', '--output_file', 'sorted_arr_sorted_rep.csv'])  
    #Read the stats from the text file

    with open('stats.txt', 'r') as f:
        stats = f.read().split(',')
        time_sorted_rep.append(float(stats[0]))
        memory_sorted_rep.append(float(stats[1]))


#Save data to a csv file
with open('results_sorted_rep.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Array Size', 'Time (s)', 'Memory (KB)'])
    for i in range(len(time_sorted_rep)):
        writer.writerow([10**(i+2), time_sorted_rep[i], memory_sorted_rep[i]])

#Plot the results using matplotlib
import matplotlib.pyplot as plt

sizes = [1e2, 1e3, 1e4, 1e5, 1e6, 1e7]
plt.figure(figsize=(10, 6))
plt.plot(sizes, time_random, marker='o', label='Random')
plt.plot(sizes, time_sorted, marker='o', label='Sorted Ascending')
plt.plot(sizes, time_sorted_desc, marker='o', label='Sorted Descending')
plt.plot(sizes, time_sorted_rep, marker='o', label='With Repeated Elements')
plt.xscale('log')
plt.xlabel('Array Size (log scale)')
plt.ylabel('Time (seconds)')
plt.title('Heap Sort Time Analysis')
plt.legend()
plt.grid(True, which="both", ls="--")
plt.tight_layout()
plt.show()

#Plot memory usage
plt.figure(figsize=(10, 6))
plt.plot(sizes, memory_random, marker='o', label='Random')
plt.plot(sizes, memory_sorted, marker='o', label='Sorted Ascending')
plt.plot(sizes, memory_sorted_desc, marker='o', label='Sorted Descending')
plt.plot(sizes, memory_sorted_rep, marker='o', label='With Repeated Elements')
plt.xscale('log')
plt.xlabel('Array Size (log scale)')
plt.ylabel('Memory Usage (KB)')
plt.title('Heap Sort Memory Usage Analysis')
plt.legend()
plt.grid(True, which="both", ls="--")
plt.tight_layout()
plt.show()